#!/bin/python

import sys


def print_usage():
    print(
        'usage: infer-tree [option] [data-file] [*initial_setting]\n'
        'option value:\n'
        'C - Inference from complete data\n'
        'E - Expectation-maximization parameter inference\n'
        'M - Maximum-probability inference\n'
        'initial_setting - E and M expect initial P values for RVs\n'
        'for example: ./infer-tree E sample.txt 0.5 0.5 0.5 0.1 0.1 ..'
    )
    exit()


def get_initial_values():
    initial_values = sys.argv[3:]
    if len(initial_values) < 10:
        print('\nwrong usage\n')
        print_usage()


def run():
    if len(sys.argv) < 3:
        print('\nwrong usage\n')
        print_usage()

    opt = sys.argv[1]
    data_file = sys.argv[2]

    if opt == 'C':
        pass
    elif opt == 'E':
        vals = get_initial_values()

    elif opt == 'M':
        vals = get_initial_values()



if __name__ == '__main__':
    run()